import { Jomolhari } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  SignInButton,
} from "@clerk/nextjs";
import Header from "@/components/Header";
const jacquard_24 = Jomolhari({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={jacquard_24.className}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
